chapterEmail: wicyskean@kean.edu
meetingDay: Tuesdays
meetingTime: 3:30 PM
meetingLocation: GLAB 208
discordUrl: https://discord.gg/jQFuee7Zf9
instagramUrl: https://www.instagram.com/wicys.kean/
instagramHandle: '@wicys.kean'
nationalUrl: https://www.wicys.org/
cougarlinkUrl: https://kean.campuslabs.com/engage/organization/wicyskean
